language: node_js
node_js:
  - node
script:
  - npm run build
deploy:
  provider: heroku
  api_key: '$HEROKU_TOKEN'
  app: 
    master: armandbot
    subspace: armand-subspace
  script: echo "Deploying to heroku ..."